openapi: 3.0.0
info:
  title: Hotelier Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /hotels:
    post:
      summary: Create a hotel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hotel'
      responses:
        '201':
          description: Hotel created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
    get:
      summary: Get a list of hotels
      responses:
        '200':
          description: List of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'

  /rooms:
    post:
      summary: Create a room for a hotel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '201':
          description: Room created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer

    get:
      summary: Get rooms
      parameters:
        - name: hotel_id
          in: query
          required: false
          schema:
            type: integer
            description: ID of the hotel to filter rooms. If not provided, returns all rooms.
      responses:
        '200':
          description: List of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'

  /hotels/{id}:
    put:
      summary: Update hotel information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Hotel updated successfully
        '404':
          description: Hotel not found
    delete:
      summary: Delete a hotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Hotel deleted successfully
        '404':
          description: Hotel not found

  /rooms/{id}:
    put:
      summary: Update room information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_number:
                  type: string
                price:
                  type: number
                  format: float
      responses:
        '200':
          description: Room updated successfully
        '404':
          description: Room not found
    delete:
      summary: Delete a room
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Room deleted successfully
        '404':
          description: Room not found

components:
  schemas:
    Hotel:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
    Room:
      type: object
      properties:
        id:
          type: integer
        hotel_id:
          type: integer
        room_number:
          type: string
        price:
          type: number
          format: float
