
services:
  hotelier-service:
    build:
      #context: D:\hotel-service-go
      context: ..
      dockerfile: /hotel-service/hotelier-service/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../configs:/app/configs
    environment:
      - CONFIG_PATH=/app/configs/hotelier-config.yaml
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotelier
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
