services:
  booking_server:
    env_file:
      - ../.env.dev
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: booking-server
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}"
    depends_on:
      - booking_db
    restart: always

  booking_db:
    env_file:
      - ../.env.dev
    image: postgres:14
    container_name: booking-db
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      HOTELIER_SERVICE_HOST: hotelier-service
      HOTELIER_SERVICE_GRPC_PORT: 50051

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: