// Package app provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package app

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Booking defines model for Booking.
type Booking struct {
	// BookingId Unique ID of the booking.
	BookingId *int `json:"bookingId,omitempty"`

	// CheckInDate Check-in date of the booking.
	CheckInDate *openapi_types.Date `json:"checkInDate,omitempty"`

	// ClientFullName Full name of the client.
	ClientFullName *string `json:"clientFullName,omitempty"`

	// ClientPhoneNumber Phone number of the client.
	ClientPhoneNumber *string `json:"clientPhoneNumber,omitempty"`

	// Duration Duration of the booking in nights.
	Duration *int `json:"duration,omitempty"`

	// HotelName Name of the hotel.
	HotelName *string `json:"hotelName,omitempty"`

	// RoomNumber Room number in the hotel.
	RoomNumber *string `json:"roomNumber,omitempty"`

	// TotalPrice Total price of the booking.
	TotalPrice *float32 `json:"totalPrice,omitempty"`
}

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	// CheckInDate Check-in date of the booking.
	CheckInDate *openapi_types.Date `json:"checkInDate,omitempty"`

	// ClientFullName Full name of the client.
	ClientFullName *string `json:"clientFullName,omitempty"`

	// ClientPhoneNumber Phone number of the client.
	ClientPhoneNumber *string `json:"clientPhoneNumber,omitempty"`

	// Duration Duration of the booking in nights.
	Duration *int `json:"duration,omitempty"`

	// HotelName Name of the hotel.
	HotelName *string `json:"hotelName,omitempty"`

	// RoomNumber Room number in the hotel.
	RoomNumber *string `json:"roomNumber,omitempty"`
}

// GetApiV1BookingsClientParams defines parameters for GetApiV1BookingsClient.
type GetApiV1BookingsClientParams struct {
	// PhoneNumber The phone number of the client.
	PhoneNumber string `form:"phoneNumber" json:"phoneNumber"`
}

// GetApiV1BookingsHotelParams defines parameters for GetApiV1BookingsHotel.
type GetApiV1BookingsHotelParams struct {
	// HotelId The unique ID of the hotel.
	HotelId int `form:"hotelId" json:"hotelId"`
}

// PostApiV1BookingsJSONRequestBody defines body for PostApiV1Bookings for application/json ContentType.
type PostApiV1BookingsJSONRequestBody = CreateBookingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a booking
	// (POST /api/v1/bookings)
	PostApiV1Bookings(ctx echo.Context) error
	// Get client bookings
	// (GET /api/v1/bookings/client)
	GetApiV1BookingsClient(ctx echo.Context, params GetApiV1BookingsClientParams) error
	// Get bookings for a specific hotel
	// (GET /api/v1/bookings/hotel)
	GetApiV1BookingsHotel(ctx echo.Context, params GetApiV1BookingsHotelParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostApiV1Bookings converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Bookings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Bookings(ctx)
	return err
}

// GetApiV1BookingsClient converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1BookingsClient(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1BookingsClientParams
	// ------------- Required query parameter "phoneNumber" -------------

	err = runtime.BindQueryParameter("form", true, true, "phoneNumber", ctx.QueryParams(), &params.PhoneNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter phoneNumber: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1BookingsClient(ctx, params)
	return err
}

// GetApiV1BookingsHotel converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1BookingsHotel(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1BookingsHotelParams
	// ------------- Required query parameter "hotelId" -------------

	err = runtime.BindQueryParameter("form", true, true, "hotelId", ctx.QueryParams(), &params.HotelId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter hotelId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1BookingsHotel(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/bookings", wrapper.PostApiV1Bookings)
	router.GET(baseURL+"/api/v1/bookings/client", wrapper.GetApiV1BookingsClient)
	router.GET(baseURL+"/api/v1/bookings/hotel", wrapper.GetApiV1BookingsHotel)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yW32/bNhDH/5UDt0fFdtbuYX5zkrXzwwIj+/EyFAMtnm22EskcT26Nwv/7cKSl2JaS",
	"Zu0KDMPebJ345f343J0+qtLXwTt0HNX0o4rlBmudfl55/866tfwM5AMSW0yGZTbMjfwxGEuyga13aqp+",
	"c/a+QZjfgF8BbxAO745UoXgXUE2VdYxrJLUvVLnB8t3c3WjGvtS1GC+sA6MZB+RWnmrNaqrE/iAfmcRp",
	"Ua8sOn7VVNWtrgcuEAs4XXfi+cDoca3Fxju8beolUl8uGcEl6zMUTUM6nzwXujlYzmIG68DZ9YbjcDI3",
	"nvGRSG+PgkyvDXpE3tePBXfnfd3GZt0nhNizrhZkywFXfhUbBDE+VdNV5TU/aOeb1X7fPfHLt1iy3HZN",
	"qBkPsN7hfYOR+8z+j9p/ELU+DvLIupXvy84Wc1h5glo7vZYYc8JAO5P12+BzzJYr0T1gBb8gbQXZ2WKu",
	"CrVFiln1cjQZTSQiH9DpYNVUvRhNRi9UoYLmTUJvrIMdby/HrX6C02dIzzhMKIMGh++7Wry3vElZCOS3",
	"1qABg6xtlfwUxFMFZRirhY88C/b3y6v2qkJR7ogrb3apD7xjdOluHUJly3R6/DZmPPL4l1/fEq7UVH0z",
	"ftgP48NyGA+2XMq93GYJjZoyNZgexOBdzE343eTyH/Oh3U7p2tM0tkWLTVlijKumqnZQJp/NSIr1cjLp",
	"J/9KGzjEAhfws41RNLxAuNWVNWBdaFhGhD6I/DBQQe9WlS1FofVCV4Ta7AA/2MgxMSjVXNstOpBGSAim",
	"yUParTGJfz/k4dwxktNVohEJfiTyBBcwc9A4/BCwZDSA6akvy4YoxbsvVGzqWtPuGLFll7+iR+g494Z4",
	"sMYBTu+QyeJWZCobWfq9PZri0xADlnZly7bLljqiAZ/a2RKEowHWx/g1nlJ8nb2RliJdIyNFNf2jt1mk",
	"RZ4cjFZeu2+QdqpQLo0vFY7m7Dm+xRGK3QpIBwZG0Zse65O/xbplrOOzoe/u10R6N9QEs640bQm68fbZ",
	"HXBatiTzcmAFeIZXvnEGLuDWH5Mhz0757yl+NfBfI59nYpj9tAy+AP3DMmmBtxxhfvNpyH9K1z6D8eb8",
	"E7vbjkN8J+PcPMn2+YL/F7N8kmsJ/jBo0LRp+Gy4c92kVF8G9pBHX5Xqx0ZvBjmlM6Ybhog6/8ARbkE+",
	"XVShGqrUVLWd8WfMr6j9m/1fAQAA//8fefYpNg4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
