# Конфигурационный файл для сервиса hotelier в формате YAML. С параметрами подключения к базе данных и порты.
database:
  host: "hotelier_db"
  port: 5432
  user: "user"
  password: "password"
  dbname: "hotelier"
  sslmode: "disable"
server:
  port: 8080
