openapi: 3.0.3
info:
  title: Payment System API
  version: "1.0.0"
  description: API for processing payments and sending webhooks to the Booking Service.

servers:
  - url: /Payment system
    description: Payment System base path

paths:
  /api/v1/payments:
    post:
      summary: Process a payment
      description: Accepts a payment request and processes the payment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '202':
          description: Payment request accepted for processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Bad Request - Invalid input data.
        '500':
          description: Internal Server Error - An unexpected error occurred.

components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        amount:
          type: number
          format: double
          description: The amount to be paid.
        bookingId:
          type: string
          description: The booking ID associated with the payment.
      required:
        - amount
        - bookingId

    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment process.