# Конфигурационный файл для сервиса hotelier в формате YAML. С параметрами подключения к базе данных и порты.
database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbname: "hotelier"
server:
  port: 8080
