// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: hotelier-service/api/protobufs/hotelier_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId    int32  `protobuf:"varint,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	RoomNumber string `protobuf:"bytes,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	mi := &file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescGZIP(), []int{0}
}

func (x *RoomRequest) GetHotelId() int32 {
	if x != nil {
		return x.HotelId
	}
	return 0
}

func (x *RoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_hotelier_service_api_protobufs_hotelier_service_proto protoreflect.FileDescriptor

var file_hotelier_service_api_protobufs_hotelier_service_proto_rawDesc = []byte{
	0x0a, 0x35, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65,
	0x72, 0x22, 0x49, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x0c,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x32, 0x50, 0x0a, 0x0f, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x65, 0x72,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescOnce sync.Once
	file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescData = file_hotelier_service_api_protobufs_hotelier_service_proto_rawDesc
)

func file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescGZIP() []byte {
	file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescOnce.Do(func() {
		file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescData)
	})
	return file_hotelier_service_api_protobufs_hotelier_service_proto_rawDescData
}

var file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotelier_service_api_protobufs_hotelier_service_proto_goTypes = []any{
	(*RoomRequest)(nil),  // 0: hotelier.RoomRequest
	(*RoomResponse)(nil), // 1: hotelier.RoomResponse
}
var file_hotelier_service_api_protobufs_hotelier_service_proto_depIdxs = []int32{
	0, // 0: hotelier.HotelierService.GetRoomPrice:input_type -> hotelier.RoomRequest
	1, // 1: hotelier.HotelierService.GetRoomPrice:output_type -> hotelier.RoomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotelier_service_api_protobufs_hotelier_service_proto_init() }
func file_hotelier_service_api_protobufs_hotelier_service_proto_init() {
	if File_hotelier_service_api_protobufs_hotelier_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hotelier_service_api_protobufs_hotelier_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotelier_service_api_protobufs_hotelier_service_proto_goTypes,
		DependencyIndexes: file_hotelier_service_api_protobufs_hotelier_service_proto_depIdxs,
		MessageInfos:      file_hotelier_service_api_protobufs_hotelier_service_proto_msgTypes,
	}.Build()
	File_hotelier_service_api_protobufs_hotelier_service_proto = out.File
	file_hotelier_service_api_protobufs_hotelier_service_proto_rawDesc = nil
	file_hotelier_service_api_protobufs_hotelier_service_proto_goTypes = nil
	file_hotelier_service_api_protobufs_hotelier_service_proto_depIdxs = nil
}
